/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek.component;

import apotek.ApotekKaryawan;
import apotek.ApotekPembelian;
import apotek.ApotekSupplier;
import apotek.RestockObat;
import apotek.swing.connectionmysql;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmad Bagus Mas'udi
 */
public class FormPembelian extends javax.swing.JPanel {

    /**
     * Creates new form FormPembelian
     */
    
    public static String Kode;
    
    public FormPembelian() {
        initComponents();
        tampilkanPembelian();
        tampilkanKaryawan();
        tampilkanSupplier();
        cbm();
        int hari, bulan, tahun;
        GregorianCalendar date = new GregorianCalendar();
        hari = date.get(Calendar.DAY_OF_MONTH);
        bulan = date.get(Calendar.MONTH);
        tahun = date.get(Calendar.YEAR);
        String tgl = Integer.toString(tahun) + "-" + (bulan + 1) + "-" + Integer.toString(hari);
        Tanggal.setText(tgl);
        
    }

    public void cbm(){
        String kdkaryawan = "";
        int i = 0;
        int kolom = tabelKaryawan.getRowCount() - 1;
        while(i <= kolom){
            kdkaryawan = tabelKaryawan.getValueAt(i, 0).toString();
            cbmKaryawan.addItem(kdkaryawan);
            i= i + 1;
        }
        
        String kdsupplier = "";
        int ii = 0;
        int kolomm = tabelSupplier.getRowCount() - 1;
        while(ii <= kolomm){
            kdsupplier = tabelSupplier.getValueAt(ii, 0).toString();
            cbmSupplier.addItem(kdsupplier);
            ii= ii + 1;
        }
       
    }
    
    public void tampilkanPembelian() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("No Supply");
        table.addColumn("Id Supplier");
        table.addColumn("Id Karyawan");
        table.addColumn("Tanggal");
        table.addColumn("Total");
        table.addColumn("Pajak");
        table.addColumn("Total Bayar");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from pembelian";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7)
                });
            }
            tabelPembelian.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    public void tampilkanKaryawan() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID_KARYAWAN");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select ID_KARYAWAN from karyawan";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1)
                });
            }
            tabelKaryawan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    public void tampilkanSupplier() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID_KARYAWAN");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select ID_SUPPLIER from supplier";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1)
                });
            }
            tabelSupplier.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelSupplier = new javax.swing.JTable();
        tabelKaryawan = new javax.swing.JTable();
        panelBorder1 = new apotek.swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembelian = new apotek.swing.Table();
        jLabel3 = new javax.swing.JLabel();
        NoSupply = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        Total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Pajak = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TotalBayar = new javax.swing.JTextField();
        cbmSupplier = new javax.swing.JComboBox<>();
        cbmKaryawan = new javax.swing.JComboBox<>();
        save1 = new javax.swing.JButton();
        save2 = new javax.swing.JButton();
        save3 = new javax.swing.JButton();

        tabelSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        setBackground(new java.awt.Color(242, 242, 242));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        tabelPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPembelian);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("No Supply");

        NoSupply.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("ID Supplier");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("ID Karyawan");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Tanggal");

        Tanggal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Total");

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(51, 51, 51));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apotek/image/che2ck.png"))); // NOI18N
        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        Total.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TotalKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Pajak");

        Pajak.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Pajak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PajakKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("Total bayar");

        TotalBayar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBayarActionPerformed(evt);
            }
        });

        cbmSupplier.setBackground(new java.awt.Color(255, 255, 255));
        cbmSupplier.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        cbmKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        cbmKaryawan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        save1.setBackground(new java.awt.Color(255, 255, 255));
        save1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        save1.setForeground(new java.awt.Color(51, 51, 51));
        save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apotek/image/trash-can (1).png"))); // NOI18N
        save1.setText("Hapus");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        save2.setBackground(new java.awt.Color(255, 255, 255));
        save2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        save2.setForeground(new java.awt.Color(51, 51, 51));
        save2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apotek/image/edit.png"))); // NOI18N
        save2.setText("Edit");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });

        save3.setBackground(new java.awt.Color(255, 255, 255));
        save3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        save3.setForeground(new java.awt.Color(51, 51, 51));
        save3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apotek/image/plus.png"))); // NOI18N
        save3.setText("Restock Obat");
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbmSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbmKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NoSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(31, 31, 31))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(51, 51, 51)))
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pajak, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Total)
                                    .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(TotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(save3)
                        .addGap(27, 27, 27)
                        .addComponent(save)
                        .addGap(28, 28, 28)
                        .addComponent(save1)
                        .addGap(27, 27, 27)
                        .addComponent(save2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Tanggal)
                            .addComponent(TotalBayar)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoSupply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(save1)
                    .addComponent(save2)
                    .addComponent(save3))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try {
            if (NoSupply.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    Connection con = connectionmysql.koneksiDB();
                    String sql = "insert into pembelian values ('" + NoSupply.getText() + "','"
                            + cbmSupplier.getSelectedItem() + "','" + cbmKaryawan.getSelectedItem() + "','" + Tanggal.getText() + "','" + Total.getText() + "','" + Pajak.getText() + "','" + TotalBayar.getText() + "')";
                    Statement S = con.createStatement();
                    S.execute(sql);
                    JOptionPane.showMessageDialog(null, "Simpan Berhasil");
                    tampilkanPembelian();
                } catch (Exception e) {
                    System.out.println(e);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ada Kesalahan Pada Data ini", "Pesan", JOptionPane.WARNING_MESSAGE);
            //hapuslayar();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void TotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalBayarActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "delete from pembelian where NO_SUPPLY = '" + NoSupply.getText() + "'";
            Statement S = con.createStatement();
            S.execute(sql);
            JOptionPane.showMessageDialog(null, "Hapus berhasil");
            new ApotekPembelian().setVisible(true);
            new ApotekPembelian().setVisible(false); 
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Hapus gagal");
        }
    }//GEN-LAST:event_save1ActionPerformed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "update pembelian set NO_SUPPLY = '"+ NoSupply.getText() +"', ID_SUPPLIER = '"+ cbmSupplier.getSelectedItem() +"', ID_KARYAWAN = '"+ cbmKaryawan.getSelectedItem() +"' , TANGGAL = '"+ Tanggal.getText() +"', TOTAL = '"+ Total.getText() +"', PAJAK = '"+ Pajak.getText() +"' , TOTAL_BAYAR = '"+ TotalBayar.getText() +"' where NO_SUPPLY = '"+ NoSupply.getText() +"'";
            Statement S = con.createStatement();
            S.execute(sql);
            JOptionPane.showMessageDialog(null, "Edit berhasil");
            new ApotekPembelian().setVisible(true);
            new ApotekPembelian().setVisible(false); 
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Edit gagal");
        }
    }//GEN-LAST:event_save2ActionPerformed

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed
        new RestockObat().setVisible(true);
    }//GEN-LAST:event_save3ActionPerformed

    private void tabelPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembelianMouseClicked
        int baris = tabelPembelian.rowAtPoint(evt.getPoint());
        
        String ns = tabelPembelian.getValueAt(baris, 0).toString();
        NoSupply.setText(ns);
        
        String is = tabelPembelian.getValueAt(baris, 1).toString();
        cbmSupplier.setSelectedItem(is);
        
        String karyawan = tabelPembelian.getValueAt(baris, 2).toString();
        cbmKaryawan.setSelectedItem(karyawan);
        
        String tgl = tabelPembelian.getValueAt(baris, 3).toString();
        Tanggal.setText(tgl);
        
        String ttl = tabelPembelian.getValueAt(baris, 4).toString();
        Total.setText(ttl);
        
        String pjk = tabelPembelian.getValueAt(baris, 5).toString();
        Pajak.setText(pjk);
        
        String tb = tabelPembelian.getValueAt(baris, 6).toString();
        TotalBayar.setText(tb);
        
        
    }//GEN-LAST:event_tabelPembelianMouseClicked

    private void PajakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PajakKeyReleased
        int ttl = Integer.parseInt(Total.getText());
        int pjk = Integer.parseInt(Pajak.getText());
        int tb = ttl + pjk;
        TotalBayar.setText(Integer.toString(tb));
    }//GEN-LAST:event_PajakKeyReleased

    private void TotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalKeyReleased
        int ttl = Integer.parseInt(Total.getText());
        int pjk = Integer.parseInt(Pajak.getText());
        int tb = ttl + pjk;
        TotalBayar.setText(Integer.toString(tb));
    }//GEN-LAST:event_TotalKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NoSupply;
    private javax.swing.JTextField Pajak;
    private javax.swing.JTextField Tanggal;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField TotalBayar;
    private javax.swing.JComboBox<String> cbmKaryawan;
    private javax.swing.JComboBox<String> cbmSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private apotek.swing.PanelBorder panelBorder1;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    private javax.swing.JButton save2;
    private javax.swing.JButton save3;
    private javax.swing.JTable tabelKaryawan;
    private apotek.swing.Table tabelPembelian;
    private javax.swing.JTable tabelSupplier;
    // End of variables declaration//GEN-END:variables
}
