/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek.component;

import apotek.ApotekKaryawan;
import apotek.swing.connectionmysql;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ahmad Bagus Mas'udi
 */
public class FormLaporanPenjualan extends javax.swing.JPanel {

    /**
     * Creates new form FormPembelian
     */
    
    public static String Kode;
    public static String tgl2;
    
    public FormLaporanPenjualan() {
        initComponents();
        tampilkanPenjualan();
    }

    public void tampilkanPenjualan() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("No Penjualan");
        table.addColumn("Id Obat");
        table.addColumn("Id Karyawan");
        table.addColumn("Id Pelanggan");
        table.addColumn("Tanggal");
        table.addColumn("Jumlah");
        table.addColumn("Total");
        table.addColumn("Pajak");
        table.addColumn("Total Bayar");
        
        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from penjualan";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8), R.getString(9)
                });
            }
            tabelLaporan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new apotek.swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelLaporan = new apotek.swing.Table();
        jLabel3 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        cbmBulan = new javax.swing.JComboBox<>();
        Print = new javax.swing.JButton();
        Reset = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        tabelLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelLaporan);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("Tahun");

        txtTahun.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Bulan");

        Update.setBackground(new java.awt.Color(255, 255, 255));
        Update.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Update.setForeground(new java.awt.Color(51, 51, 51));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apotek/image/reload.png"))); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        cbmBulan.setBackground(new java.awt.Color(255, 255, 255));
        cbmBulan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbmBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        Print.setBackground(new java.awt.Color(255, 255, 255));
        Print.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Print.setForeground(new java.awt.Color(51, 51, 51));
        Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apotek/image/print.png"))); // NOI18N
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(255, 255, 255));
        Reset.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Reset.setForeground(new java.awt.Color(51, 51, 51));
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apotek/image/reload.png"))); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbmBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(Update)
                        .addGap(18, 18, 18)
                        .addComponent(Reset)
                        .addGap(18, 18, 18)
                        .addComponent(Print)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbmBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Print)
                    .addComponent(Reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       String bln = "";
        if (cbmBulan.getSelectedIndex() < 10){
            bln = "0" + cbmBulan.getSelectedIndex();
        } else if (cbmBulan.getSelectedIndex() >= 10){
            bln = "" + cbmBulan.getSelectedIndex();
        }
        
        tgl2 = "'%"+txtTahun.getText() + "-"+ bln +"%'";
        
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("No Penjualan");
        table.addColumn("Id Obat");
        table.addColumn("Id Karyawan");
        table.addColumn("Id Pelanggan");
        table.addColumn("Tanggal");
        table.addColumn("Jumlah");
        table.addColumn("Total");
        table.addColumn("Pajak");
        table.addColumn("Total Bayar");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from penjualan where TANGGAL LIKE "+tgl2+"";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8), R.getString(9)
                });
            }
            tabelLaporan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        String bln = "";
        if (cbmBulan.getSelectedIndex() < 10){
            bln = "0" + cbmBulan.getSelectedIndex();
        } else if (cbmBulan.getSelectedIndex() >= 10){
            bln = "" + cbmBulan.getSelectedIndex();
        }
        
        File reportFile = new File(".");
        String dirr = "";    
       

        if (txtTahun.getText().equals("")) {
            try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from penjualan";
            Statement S = con.createStatement();
            dirr = reportFile.getCanonicalPath() + "/src/apotek/report/";
            JasperDesign design = JRXmlLoader.load(dirr + "Penjualan.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = S.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JasperViewer.viewReport(jp);
        } catch (SQLException | IOException ex) {
            JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex, "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } catch (JRException ex) {
            
        } 
        } else {
         try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from penjualan where TANGGAL LIKE '%" + txtTahun.getText() + "-"+ bln +"%'";
            Statement S = con.createStatement();
            dirr = reportFile.getCanonicalPath() + "/src/apotek/report/";
            JasperDesign design = JRXmlLoader.load(dirr + "Penjualan.jrxml");
            HashMap hash = new HashMap();
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = S.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, hash, rsDataSource);
            JasperViewer.viewReport(jp);
        } catch (SQLException | IOException ex) {
            JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex, "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } catch (JRException ex) {
            
        } 
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        tampilkanPenjualan();
    }//GEN-LAST:event_ResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> cbmBulan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private apotek.swing.PanelBorder panelBorder1;
    private apotek.swing.Table tabelLaporan;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
